# Dockerfile_celery_worker

FROM python:3.12-slim

WORKDIR /app

# Copy dependency files for installation
COPY pyproject.toml poetry.lock /app/

# Install Python dependencies
RUN pip install --upgrade pip && pip install poetry
RUN poetry config virtualenvs.create false && poetry install --no-dev

# Copy the entire project code into the container
COPY . /app

# Set Celery environment variables for PostgreSQL
ENV CELERY_BROKER_URL=postgresql://user:password@postgres:5432/db_name
ENV CELERY_RESULT_BACKEND=postgresql://user:password@postgres:5432/db_name

# Run Celery Worker with logging
CMD ["celery", "-A", "project_name", "worker", "--loglevel=info"]
