# Dockerfile_youtube_downloader for Download Service
FROM python:3.12-slim

# Install system dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    ffmpeg \
    && rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /app

# Copy only the necessary files for dependencies first
COPY pyproject.toml poetry.lock /app/

# Install Poetry
RUN pip install --upgrade pip && \
    pip install poetry

# Configure Poetry to not use virtual environments
RUN poetry config virtualenvs.create false && poetry install --no-dev

# Copy the rest of the application code
COPY . /app

# Expose the necessary ports if needed (optional)
# EXPOSE 8000

# Define the default command
CMD ["poetry", "run", "python", "-m", "src.download_pipeline.youtube_downloader"]
